### ISSUE TITLE
Cant find file's dependency.

### ISSUE THREAD

**Issue by reggi** [yamadapc/jsdoctest#13]
I have a module `argx` and It doesn't seem to work. None of the example include modules either. :(

```
thomas@workstation:wiskers$ jsdoctest ./standard-fn-name.js 
module.js:334
    throw err;
          ^
Error: Cannot find module 'argx'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/thomas/Desktop/wiskers/standard-fn-name.js:1:74)
    at Module._compile (module.js:426:26)
    at Object.jsdoctest$run [as run] (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/jsdoctest/lib/index.js:26:10)
    at Object.exports.run (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/jsdoctest/lib/cli/index.js:48:28)
    at Object.<anonymous> (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/jsdoctest/bin/jsdoctest:4:5)
    at Module._compile (module.js:426:26)
```

**Comment by yamadapc** [comment]
Are you certain your module is installed and `mocha` is being run from a path it can access the module?

[I've just added an example which `require`s `lodash` and it works.](https://github.com/yamadapc/jsdoctest/blob/8b2e3191d51ebfe5dd62f08adc22d50db1243308/examples/requiring-other-modules.js)

Pretty confident this isn't this module's problem. Hit me up on [Gitter](https://gitter.im/yamadapc/jsdoctest) or e-mail and I'll help you out.

**Comment by reggi** [comment]
I think your right.
